### ISSUE TITLE
RFC: make asm_parser private

### ISSUE THREAD

**Issue by qmonnet** [qmonnet/rbpf#13]
I do not see any particular reason to offer the `asm_parser` to the end user. As I see it, all the assembler API holds in the `assembler` module. What about making `asm_parser` private in `src/lib.rs`? @rlane, any thought?

Note that as a consequence, we would have to move the tests from the separate file to a `test` module at the end of file `src/asm_parser.rs`. (I don't think the function/stucts from the module would remain accessible otherwise).

**Comment by rlane** [comment]
Sounds good.
