### ISSUE TITLE
macOS build fails due to clock_gettime usage

### ISSUE THREAD

**Issue by waywardmonkeys** [qmonnet/rbpf#19]
macOS doesn't have `clock_gettime` or `CLOCK_MONOTONIC`, so the `bpf_time_getns` helper function fails to compile on macOS.

**Comment by qmonnet** [comment]
Thanks for the report. I don't have a machine running macOS at hand so I've never tried compiling rbpf on this OS, would you know what function we could use instead?

**Comment by waywardmonkeys** [comment]
I was just looking at preparing a patch that uses `std::time::{Instant,Duration}` (https://doc.rust-lang.org/std/time/struct.Instant.html) instead ...

**Comment by waywardmonkeys** [comment]
Well, that won't work... but I'll submit a pull request that fixes on macOS within a day.

**Comment by qmonnet** [comment]
No hurry here, thanks a lot!

**Comment by badboy** [comment]
While at it we could add MacOS as a target on Travis to make sure it continues to work

**Comment by qmonnet** [comment]
Yeah, that's a good idea. We can do that once this bug is fixed and we have something that compiles.

While we're at it, I've not tried on Windows, either. I don't know if it compiles (the `clock_gettime` probably fails as well, but what else?). Has anyone here tried to work with Rust on Windows?

**Comment by badboy** [comment]
[AppVeyor](https://www.appveyor.com/) is free and easy to setup as CI as well to run the build. The jitting might be incompatible, but the rest should probably work.

**Comment by waywardmonkeys** [comment]
My change to use the `time` crate will let that code at least work on Windows. I can't speak to any of the rest of it.

**Comment by badboy** [comment]
I can take care of an AppVeyor config today

**Comment by qmonnet** [comment]
@waywardmonkeys: Your patch works fine on Linux, thanks a lot! There is just a sentence that we should remove from the comment of the function, see review in the PR.

@badboy: Thanks a lot, I'd be glad to let you have a look. Tell me if you need some specific rights on the repo to make this work.

I really appreciate your help and motivation! :-)

**Comment by waywardmonkeys** [comment]
@qmonnet I'll fix up the PR shortly. Dinner time here!

**Comment by qmonnet** [comment]
No problem. _Bon appétit_!
