### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by qmonnet** [qmonnet/rbpf#24]
The `README.md` file is somewhat outdated. In particular:

* It should mention the systems rbpf can be compiled on (Linux/MacOS, Windows as well but without the JIT (see #21)).
* It does not mention the API created some time ago to build the BPF programs.
* There are probably a lot of other items to update.

If you stumble on something else, do not hesitate to add elements to update below, so that I do not forget them the day I dive into this!

**Comment by jackcmay** [comment]
(let me know if I should ask this question someplace other than this issue)

What API to build BPF programs are you referring to?

**Comment by qmonnet** [comment]
No problem :)

That would be [this one](https://github.com/qmonnet/rbpf/commit/724fee58cb2c7773dce94992b7d5b1cb9144185d).

**Comment by qmonnet** [comment]
Well maybe there is not that much to change after all. I pushed a couple of commit in that direction:

* ba86c5277416a5d5ca5425d865627fcddd0fb040
* 6691d231acea57ab2a35e62f9c6fa29d280c2070
* ba86c5277416a5d5ca5425d865627fcddd0fb040

And I believe we're mostly good. I ran the tests and they still pass (I just pushed one fix). Another update will be needed when we merge the PR for returning errors from the verifier, but I pushed the change to the related branch already... So let's close here. Everyone, feel free to reopen if you spot other things to change or update on the README.
