### ISSUE TITLE
Tag a new crate version and push it to crates.io

### ISSUE THREAD

**Issue by qmonnet** [qmonnet/rbpf#32]
We want to tag a new version and update the crate available for download on crates.io.

ETA: end of this month.

There have been quite some changes since last version, although I'm not sure the current version is stable enough to deserve 1.0.0. Therefore I consider bumping version number to **0.1.0**.

Things we want to fix and complete before that:
- Merging #31 (propagate errors instead of panicking in verifier).
- Possibly doing the same thing at other parts of the crate? That would be to complete #30.
- Address #29 (provide a way to pass a custom verifier).
- Check if dependencies can be updated to newer releases without breaking the lib / the tests. (#35)
- Does anyone need anything else?

**Comment by jackcmay** [comment]
Anything left after #39 and #40 are merged?

**Comment by qmonnet** [comment]
Hmm maybe just one minor nit. I liked the type you declared for a verifier:

```rust
pub type Verifier = fn(prog: &[u8]) -> Result<(), Error>;
```

Do you think it would be worth doing the same for the helpers? So that instead of:

```rust
pub fn register_helper(&mut self,
                       key: u32,
                       function: fn (u64, u64, u64, u64, u64) -> u64) 
                       -> Result<(), Error>
```

... we'd have something like:

```rust
pub fn register_helper(&mut self,
                       key: u32,
                       function: Helper) -> Result<(), Error>
```

(`EbpfHelper` or `Helper`, I don't really know what sounds best. Maybe just `Helper` if people call that with the `rbpf::` prefix already?)

I'm not trying to give you more work and can do it if you want :).

Apart from that, I can't think of anything in particular from my side.

**Comment by jackcmay** [comment]
Sure, I'll take a crack at it, can you file an issue

**Comment by jackcmay** [comment]
@qmonnet Can you provide an ETA of when this can be pushed to crates.io?

**Comment by qmonnet** [comment]
Just published it now :).

**Comment by jackcmay** [comment]
Thanks!
https://github.com/solana-labs/solana/blob/24b513c3c7cd5bc022391b2bdcfbf304c87483e6/programs/native/bpf_loader/Cargo.toml#L13
