### ISSUE TITLE
Update dependencies in preparation for release

### ISSUE THREAD

**Issue by jackcmay** [qmonnet/rbpf#35]
Updating dependency `combine` from 2.1.1 to 3.6 will require some code rework since there were non-compatible api changes.

Updating the rest of the dependencies to the following did not change any test results:

 combine = "2.1.1"
-libc = "0.2.0"
+libc = "0.2"
 time = "0.1"
-byteorder = "1.2.1"
+byteorder = "1.2"
 
 [dev-dependencies]
 
 elf = "0.0.10"
-json = "0.11.4"
+json = "0.11"

**Comment by qmonnet** [comment]
Thanks! I had a look at combine, I don't believe it's worth changing the code to compile with 3.6.0 at the moment. We can still update to 2.5, though.

I'll push a commit with those changes.
