### ISSUE TITLE
Valid mod operations cause a div/0 exception

### ISSUE THREAD

**Issue by jackcmay** [qmonnet/rbpf#45]
https://github.com/qmonnet/rbpf/blob/ceb7fa67946a7a6e9cff5a4e03ae721a1ecf10b6/src/jit.rs#L380

**Comment by jackcmay** [comment]
Looks like this was done on purpose, why?

**Comment by qmonnet** [comment]
I took this code from uBPF, so I'm not exactly the “original author” here :).

As I understand it this should be a conditional jump, triggered only if the divisor is 0 — in which case this _is_ the behaviour we expect to see. How did you trigger it? Are you sure you were not trying to divide by 0?

**Comment by jackcmay** [comment]
Yeah, was triggered by a `x % 10`

**Comment by qmonnet** [comment]
I didn't manage to reproduce it :/. Do you have a reproducer, by any chance?

**Comment by qmonnet** [comment]
Possibly related to https://github.com/qmonnet/rbpf/pull/89
