### ISSUE TITLE
logo update for dark theme

### ISSUE THREAD

**Issue by errordeveloper** [qmonnet/rbpf#50]
The logo could probably use some tweaks to look well in the dark theme:

![Screenshot 2020-12-15 at 10 25 14](https://user-images.githubusercontent.com/251467/102203199-32b07480-3ec0-11eb-8b4e-aa0e633c26dc.png)

**Comment by qmonnet** [comment]
Fixed with 6c524b3669d7b19736ceaf8d155b43aee93479c3, thanks!

**Comment by errordeveloper** [comment]
nice solution actually!
